export const ADD_COUNT = 'ADD_COUNT';
export const REDUCE_COUNT = 'REDUCE_COUNT';
export const ADD_NUMBER = 'ADD_NUMBER';
export const REDUCE_NUMBER = 'REDUCE_NUMBER';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const SET_DASHBOARDLIST = 'SET_DASHBOARDLIST';
