export default {
  CART_AMOUNT_INCREMENT: 'CART_AMOUNT_INCREMENT', // 增加amout
  CART_AMOUNT_DECREMENT: 'CART_AMOUNT_DECREMENT', // 减少amount
  
  START_FETCH_BLOG_LIST: 'START_FETCH_BLOG_LIST',
  FETCH_BLOG_LIST_SUCCESS: 'FETCH_BLOG_LIST_SUCCESS',
  FETCH_BLOG_LIST_FAILED: 'FETCH_BLOG_LIST_FAILED',
}